[package]
name = "specd-store"
edition.workspace = true
version.workspace = true

[dependencies]
specd-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile = "3"
